use LIBRARYDB;
--CREATE TRIGGER KITAPDURUM1
--ON TBL_DEPOSIT
--AFTER INSERT
--AS
--DECLARE @KITAP INT
--SELECT @KITAP=BOOKID FROM inserted
--UPDATE TBL_BOOK SET STATUS=0 WHERE ID=@KITAP

CREATE TRIGGER KITAPDURUM3
ON TBL_DEPOSIT
AFTER UPDATE
AS
DECLARE @KITAP INT
SELECT @KITAP=BOOKID FROM inserted
UPDATE TBL_BOOK SET STATUS=1 WHERE ID=@KITAP