--CREATE PROCEDURE ENFAZLAKITAPYAZAR
--AS
--SELECT TOP 1 TBL_AUTHOR.NAME + TBL_AUTHOR.SURNAME  FROM TBL_BOOK 
--INNER JOIN TBL_AUTHOR ON TBL_AUTHOR.ID=TBL_BOOK.AUTHORID
--GROUP BY TBL_AUTHOR.NAME,TBL_AUTHOR.SURNAME ORDER BY COUNT(*) DESC

execute enfazlakýtapyazar